### ISSUE TITLE
Infografia Hilos

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/infografia-de-hilos-MarcoRg06#2]
[Infografía HilosMarco Uriel Rosas Garcia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-MarcoRg06/files/15067524/Infografia.HilosMarco.Uriel.Rosas.Garcia.pdf)

**Comment by Kevinosorio77** [comment]
De acuerdo ala rubrica cumple con los estándares de creatividad, diseño, composición y incluye todas las indicaciones 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
